-- MySQL Script generated by MySQL Workbench
-- Fri 05 Jun 2015 09:58:47 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema findme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema findme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `findme` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `findme` ;

-- -----------------------------------------------------
-- Table `findme`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`persons` (
  `idPerson` CHAR(36) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `emailAddress` VARCHAR(45) NOT NULL,
  `personSalt` VARCHAR(50) NULL,
  `personHashPassword` VARCHAR(250) NULL,
  `areaCode` VARCHAR(10) NULL,
  `phoneNumber` VARCHAR(15) NULL,
  `location` VARCHAR(45) NULL,
  `deskLocation` VARCHAR(10) NULL,
  `department` VARCHAR(45) NULL,
  `jobTitle` VARCHAR(45) NULL,
  `currentTeam` VARCHAR(45) NULL,
  `currentProject` VARCHAR(45) NULL,
  `details` VARCHAR(260) NULL,
  `photo` VARCHAR(400) NULL,
  `status` ENUM('Active','Inactive','On Leave') NOT NULL,
  `isDailyPerson` TINYINT(1) NULL DEFAULT 0,
  `isBonusPerson` TINYINT(1) NULL DEFAULT 0,
  UNIQUE INDEX `emailAddress_UNIQUE` (`emailAddress` ASC),
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `personSalt_UNIQUE` (`personSalt` ASC),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findme`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`teams` (
  `idTeams` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(45) NULL,
  `teamMainLocation` VARCHAR(45) NULL,
  `teamDescription` VARCHAR(280) NULL,
  `status` ENUM('Active','Inactive') NOT NULL,
  PRIMARY KEY (`idTeams`),
  UNIQUE INDEX `teamName_UNIQUE` (`teamName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findme`.`personTeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`personTeams` (
  `Persons_idPerson` CHAR(36) NOT NULL,
  `Teams_idTeams` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `status` ENUM('Active','Inactive') NOT NULL,
  INDEX `fk_PersonTeams_Teams1_idx` (`Teams_idTeams` ASC),
  PRIMARY KEY (`Persons_idPerson`, `Teams_idTeams`),
  CONSTRAINT `fk_PersonTeams_Persons1`
    FOREIGN KEY (`Persons_idPerson`)
    REFERENCES `findme`.`persons` (`idPerson`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_PersonTeams_Teams1`
    FOREIGN KEY (`Teams_idTeams`)
    REFERENCES `findme`.`teams` (`idTeams`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findme`.`personStickerBookConnection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`personStickerBookConnection` (
  `idPerson` CHAR(36) NOT NULL,
  `idConnectedPerson` CHAR(36) NOT NULL,
  INDEX `fk_personLineManager_persons2_idx` (`idConnectedPerson` ASC),
  CONSTRAINT `fk_personLineManager_persons1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `findme`.`persons` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personLineManager_persons2`
    FOREIGN KEY (`idConnectedPerson`)
    REFERENCES `findme`.`persons` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findme`.`gameData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`gameData` (
  `idPerson` CHAR(36) NOT NULL,
  `gameScore` INT NOT NULL DEFAULT 0,
  `stickerbookScore` INT NOT NULL DEFAULT 0,
  `lastGameEntry` DATE NULL,
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC),
  PRIMARY KEY (`idPerson`),
  CONSTRAINT `fk_leaderboards_persons1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `findme`.`persons` (`idPerson`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findme`.`competitionData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findme`.`competitionData` (
  `idPerson` CHAR(36) NOT NULL,
  `guess` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC),
  CONSTRAINT `fk_competitionData_persons1`
    FOREIGN KEY (`idPerson`)
    REFERENCES `findme`.`persons` (`idPerson`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE USER 'findme' IDENTIFIED BY '531c1474-d88a-4a73-bd36-e7e3cea8050a';

GRANT ALL ON `findme`.* TO 'findme';
GRANT SELECT ON TABLE `findme`.* TO 'findme';
GRANT SELECT, INSERT, TRIGGER ON TABLE `findme`.* TO 'findme';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `findme`.* TO 'findme';
CREATE USER 'findmeLogin' IDENTIFIED BY '305fe048-7a9c-41c6-b3db-35a3712edee7';

GRANT SELECT ON TABLE `findme`.* TO 'findmeLogin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
